name:        fossilhash
version:     0.1.7.1
synopsis:    Compile fossil revision info into Haskell projects
description: Please see the README.
category:    Development
author:      Robin Palotai, Michael Snoyman, Adam C. Foltzer
maintainer:  palotai.robin@gmail.com
license:     BSD3
github:      robinp/fossilhash

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.9.1 && < 5
- bytestring
- directory
- filepath
- template-haskell
- th-compat
- process

library:
  source-dirs: src

tests:
  fossilhash-spec:
    source-dirs: test
    main:        Spec.hs
    dependencies:
    - fossilhash
    - hspec
    - temporary
    - unliftio
